# Generated by Django 2.1.4 on 2018-12-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='image_src',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
