# Generated by Django 2.1.4 on 2018-12-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claim_image_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='image_src',
            field=models.CharField(max_length=1000),
        ),
    ]
