# Generated by Django 2.1.3 on 2019-03-20 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=250)),
                ('verdict_date', models.DateField()),
                ('label', models.CharField(max_length=50)),
                ('system_label', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='claims.Claim')),
                ('down_votes', models.ManyToManyField(blank=True, related_name='comment_down_votes', to=settings.AUTH_USER_MODEL)),
                ('up_votes', models.ManyToManyField(blank=True, related_name='comment_up_votes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
