# Generated by Django 2.1.4 on 2019-03-04 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_auto_20181219_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='neg_votes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='pos_votes',
        ),
        migrations.AddField(
            model_name='comment',
            name='down_votes',
            field=models.ManyToManyField(blank=True, related_name='down_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='system_label',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='up_votes',
            field=models.ManyToManyField(blank=True, related_name='up_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='verdict_date',
            field=models.DateField(),
        ),
    ]
