# Generated by Django 2.1.4 on 2019-02-18 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_auto_20181219_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='neg_votes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='pos_votes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='tags',
        ),
        migrations.AddField(
            model_name='comment',
            name='down_votes',
            field=models.ManyToManyField(blank=True, related_name='down_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='system_label',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='up_votes',
            field=models.ManyToManyField(blank=True, related_name='up_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
