# Generated by Django 2.1.4 on 2018-12-17 12:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=50)),
                ('authentic_grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('verdict_date', models.DateField(default=datetime.date.today)),
                ('tags', models.CharField(max_length=250)),
                ('label', models.CharField(max_length=50)),
                ('pos_votes', models.IntegerField()),
                ('neg_votes', models.IntegerField()),
                ('claims', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Claim')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=20)),
                ('reputation', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.User'),
        ),
    ]
