# Generated by Django 2.1.3 on 2019-03-14 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.IntegerField()),
                ('username', models.TextField()),
                ('action', models.TextField()),
                ('result', models.BooleanField(default=False)),
            ],
        ),
    ]
