# Generated by Django 2.1.4 on 2019-03-04 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logger',
            old_name='activity',
            new_name='action',
        ),
        migrations.AddField(
            model_name='logger',
            name='result',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='logger',
            name='user_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logger',
            name='username',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logger',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
